#!/usr/bin/env bash
#
# setup_azure.sh — Provision the Weaver runtime stack on an Azure VM.
#
# Run this on the Azure VM after terraform apply. It:
#   1. Updates the system and installs base packages
#   2. Creates the Python venv and installs dependencies
#   3. Downloads the Soul Voice GGUF from your local machine
#   4. Installs systemd units for all Weaver services
#   5. Configures Caddy with TLS
#   6. Sets up the avatar Blob Storage upload
#
# Usage:
#   sudo bash deploy/setup_azure.sh
#
# Prerequisites:
#   - Run as ubuntu on the Azure VM
#   - .env populated with AZURE_OPENAI_KEY, AZURE_SPEECH_KEY, etc.
#   - Caddy binary in /usr/bin/caddy or installed via apt

set -euo pipefail

# ── Config ────────────────────────────────────────────────────────────────────
WEAVER_HOME="$HOME/weaver/CascadeProjects/windsurf-project"
ORACLE_HOST="${ORACLE_HOST:-weaverv3.com}"
WEAVER_HEADLESS_HOST="${WEAVER_HEADLESS_HOST:-headless.weaverv3.com}"
WEAVER_DASH_HOST="${WEAVER_DASH_HOST:-dash.weaverv3.com}"
WEAVER_STATUS_HOST="${WEAVER_STATUS_HOST:-status.weaverv3.com}"
CLOUD="${CLOUD:-azure}"

echo "=== Weaver Azure Setup ==="
echo "WEAVER_HOME: $WEAVER_HOME"
echo "HOSTS: $ORACLE_HOST / $WEAVER_HEADLESS_HOST / $WEAVER_DASH_HOST / $WEAVER_STATUS_HOST"

# ── Step 1: System packages ────────────────────────────────────────────────────
echo "--- Installing system packages ---"
sudo apt-get update -qq
sudo apt-get install -y -qq \
    python3 python3-pip python3-venv \
    curl wget git \
    build-essential gcc g++ \
    libgl1 libglib2.0-0 \
    alsa-utils \
    cmake pkg-config \
    nvtop htop iotop \
    unzip

# ── Step 2: Core Weaver venv ────────────────────────────────────────────────────
echo "--- Creating Python venv ---"
cd "$WEAVER_HOME"
python3 -m venv venv
source venv/bin/activate

echo "--- Installing Python dependencies ---"
pip install --no-cache-dir --upgrade pip setuptools wheel

# Install core requirements without AWS-specific packages
sed -i '/^boto3/d' requirements-core.txt 2>/dev/null || true
sed -i '/^aws-sdk-bedrock/d' requirements-core.txt 2>/dev/null || true
sed -i '/^smithy-aws/d' requirements-core.txt 2>/dev/null || true

pip install --no-cache-dir -r requirements-core.txt

# Azure SDKs
pip install --no-cache-dir \
    openai \
    azure-identity>=1.18.0 \
    azure-cognitiveservices-speech>=1.41.0 \
    azure-storage-blob>=12.23.0

# llama-cpp-python with OpenBLAS for ARM performance
echo "--- Installing llama-cpp-python (OpenBLAS) ---"
CMAKE_ARGS="-DLLAMA_OPENBLAS=on" pip install --no-cache-dir llama-cpp-python[server]

# ── Step 3: Avatar assets → Blob Storage ────────────────────────────────────────
echo "--- Uploading avatar assets to Azure Blob Storage ---"
if [ -n "${AZURE_STORAGE_CONNECTION_STRING:-}" ]; then
    pip install --no-cache-dir azure-storage-blob
    python3 -c "
import os, glob
from azure.storage.blob import BlobServiceClient
conn = os.environ['AZURE_STORAGE_CONNECTION_STRING']
svc = BlobServiceClient.from_connection_string(conn)
container = svc.get_container_client('avatar')
avatar_dir = os.path.join(os.path.dirname('$WEAVER_HOME'), 'avatar')
for root, dirs, files in os.walk(avatar_dir):
    for fname in files:
        path = os.path.join(root, fname)
        blob_name = os.path.relpath(path, avatar_dir)
        print(f'  uploading {blob_name}...')
        with open(path, 'rb') as data:
            container.upload_blob(name=blob_name, data=data, overwrite=True)
print('Avatar assets uploaded to Blob Storage.')
"
else
    echo "  AZURE_STORAGE_CONNECTION_STRING not set — skipping Blob upload."
    echo "  Upload manually or set it and re-run."
fi

# ── Step 4: Configure .env ──────────────────────────────────────────────────────
echo "--- Configuring .env ---"
if [ ! -f .env ]; then
    cat > .env <<- ENVEOF
# Weaver Azure Environment — generated by setup_azure.sh
# Override with your actual values.

# Azure OpenAI (primary model backend)
AZURE_OPENAI_KEY=
AZURE_OPENAI_ENDPOINT=https://ydn-mp0oxh6q-eastus2.cognitiveservices.azure.com/
AZURE_OPENAI_API_VERSION=2024-12-01-preview
AZURE_OPENAI_DEPLOYMENT=gpt-4.1-mini
AZURE_OPENAI_NANO_DEPLOYMENT=gpt-4.1-nano

# Azure Speech Services (replaces AWS Polly + Nova Sonic)
AZURE_SPEECH_KEY=
AZURE_SPEECH_REGION=eastus

# Weaver LLM backend
WEAVER_LLM_BACKEND=azure
WEAVER_LLM_KEY=$(python3 -c "import secrets; print(secrets.token_hex(24))")

# Service URLs
NEXUS_BUS_URL=ws://localhost:9999
N8N_WEBHOOK_URL=http://localhost:5678/webhook/weaver-input
LORA_API_URL=http://localhost:8899/v1/chat/completions
QUANTUM_BIAS_URL=http://localhost:9997/quantum/bias

# Optional legacy keys (leave blank if unused)
MANTLE_API_KEY=
GEMINI_API_KEY=
IBM_QUANTUM_TOKEN=
TWILIO_ACCOUNT_SID=
TWILIO_AUTH_TOKEN=
ENVEOF
    echo "  .env created — edit it to fill in AZURE_OPENAI_KEY and AZURE_SPEECH_KEY."
else
    echo "  .env already exists, leaving it alone."
fi

# ── Step 5: Systemd units ───────────────────────────────────────────────────────
echo "--- Installing systemd units ---"
sudo mkdir -p /etc/systemd/system/

# weaver-llm.service — llama.cpp expert lobes
sudo tee /etc/systemd/system/weaver-llm.service > /dev/null << 'SERVICEOF'
[Unit]
Description=Weaver LLM Expert Lobes (llama.cpp)
After=network.target

[Service]
Type=simple
User=ubuntu
WorkingDirectory=/home/ubuntu/weaver/CascadeProjects/windsurf-project
ExecStart=/home/ubuntu/weaver/CascadeProjects/windsurf-project/venv/bin/python3 -m llama_cpp.server \
    --model /home/ubuntu/weaver/CascadeProjects/windsurf-project/weaver_merged_1B_Q4_K_M.gguf \
    --host 127.0.0.1 --port 8090 --n_ctx 4096 --n_gpu_layers 0
Restart=always
RestartSec=10
EnvironmentFile=/home/ubuntu/weaver/CascadeProjects/windsurf-project/.env
NoNewPrivileges=true
MemoryMax=12G
CPUQuota=80%

[Install]
WantedBy=multi-user.target
SERVICEOF

# weaver-brain.service — Bedrock Brain API (Azure OpenAI version)
sudo tee /etc/systemd/system/weaver-brain.service > /dev/null << 'SERVICEOF'
[Unit]
Description=Weaver Brain API (Azure OpenAI)
After=network.target weaver-llm.service
Wants=weaver-llm.service

[Service]
Type=simple
User=ubuntu
WorkingDirectory=/home/ubuntu/weaver/CascadeProjects/windsurf-project
ExecStartPre=/bin/bash -c 'while ! curl -sf http://127.0.0.1:8090/v1/models > /dev/null 2>&1; do sleep 2; done'
ExecStart=/home/ubuntu/weaver/CascadeProjects/windsurf-project/venv/bin/python3 -m uvicorn bedrock_brain_api:app \
    --host 127.0.0.1 --port 8093 --log-level warning --workers 1
Restart=always
RestartSec=15
EnvironmentFile=/home/ubuntu/weaver/CascadeProjects/windsurf-project/.env
Environment=WEAVER_BRAIN_PORT=8093
NoNewPrivileges=true
MemoryMax=4G

[Install]
WantedBy=multi-user.target
SERVICEOF

# weaver.service — Weaver core (headless)
sudo tee /etc/systemd/system/weaver.service > /dev/null << 'SERVICEOF'
[Unit]
Description=Weaver Core (Headless)
After=network.target weaver-llm.service
Wants=weaver-llm.service

[Service]
Type=simple
User=ubuntu
WorkingDirectory=/home/ubuntu/weaver/CascadeProjects/windsurf-project
ExecStartPre=/bin/bash -c 'while ! curl -sf http://127.0.0.1:8090/v1/models > /dev/null 2>&1; do sleep 2; done'
ExecStart=/home/ubuntu/weaver/CascadeProjects/windsurf-project/venv/bin/python3 weaver.py --headless
Restart=always
RestartSec=15
EnvironmentFile=/home/ubuntu/weaver/CascadeProjects/windsurf-project/.env
Environment=WEAVER_CODEBASE_ROOT=/home/ubuntu/weaver
Environment=WEAVER_VAULT_DIR=/home/ubuntu/weaver/CascadeProjects/windsurf-project/Nexus_Vault
NoNewPrivileges=true
MemoryMax=8G

[Install]
WantedBy=multi-user.target
SERVICEOF

# weaver-tts.service — Azure Speech TTS
sudo tee /etc/systemd/system/weaver-tts.service > /dev/null << 'SERVICEOF'
[Unit]
Description=Weaver TTS (Azure Speech)
After=network.target

[Service]
Type=simple
User=ubuntu
WorkingDirectory=/home/ubuntu/weaver/CascadeProjects/windsurf-project
ExecStart=/home/ubuntu/weaver/CascadeProjects/windsurf-project/venv/bin/python3 \
    deploy/tts/tts_server.py
Restart=always
RestartSec=10
EnvironmentFile=/home/ubuntu/weaver/CascadeProjects/windsurf-project/.env
Environment=TTS_PROVIDER=azure
Environment=TTS_HOME=/home/ubuntu/tts
NoNewPrivileges=true
MemoryMax=2G

[Install]
WantedBy=multi-user.target
SERVICEOF

# n8n.service
sudo tee /etc/systemd/system/n8n.service > /dev/null << 'SERVICEOF'
[Unit]
Description=Weaver n8n Workflow Engine
After=docker.service
Requires=docker.service

[Service]
Type=simple
User=ubuntu
ExecStartPre=/usr/bin/docker pull docker.n8n.io/n8nio/n8n:latest
ExecStart=/usr/bin/docker run --rm --name weaver-n8n \
    -p 127.0.0.1:5678:5678 \
    -e N8N_HOST=0.0.0.0 \
    -e N8N_LISTEN_ADDRESS=0.0.0.0 \
    -e N8N_PORT=5678 \
    -e WEBHOOK_URL=http://localhost:5678/ \
    -e N8N_DISABLE_UI=true \
    -e EXECUTIONS_TIMEOUT=115 \
    -e EXECUTIONS_TIMEOUT_MAX=115 \
    -e N8N_CONCURRENCY_PRODUCTION_LIMIT=4 \
    -e GENERIC_TIMEZONE=America/New_York \
    -v n8n_data:/home/node/.n8n \
    --read-only \
    --tmpfs /tmp:rw,noexec,nosuid,nodev,size=256m \
    --memory 2g --cpus 2.0 \
    --restart unless-stopped \
    docker.n8n.io/n8nio/n8n:latest
Restart=always
RestartSec=15
NoNewPrivileges=true

[Install]
WantedBy=multi-user.target
SERVICEOF

# ── Step 6: Reload systemd + enable units ──────────────────────────────────────
echo "--- Enabling systemd units ---"
sudo systemctl daemon-reload
sudo systemctl enable weaver-llm.service
sudo systemctl enable weaver-brain.service
sudo systemctl enable weaver.service
sudo systemctl enable weaver-tts.service
sudo systemctl enable n8n.service

# ── Step 7: Install Caddy ───────────────────────────────────────────────────────
echo "--- Installing Caddy ---"
if ! command -v caddy &> /dev/null; then
    sudo apt-get install -y -qq debian-keyring debian-archive-keyring apt-transport-https
    curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' | sudo gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg
    curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' | sudo tee /etc/apt/sources.list.d/caddy-stable.list
    sudo apt-get update -qq
    sudo apt-get install -y -qq caddy
fi

# ── Step 8: Configure Caddy ─────────────────────────────────────────────────────
echo "--- Configuring Caddy ---"
mkdir -p /var/www/weaver /var/www/weaver-headless

# We need to modify Caddyfile with proper env var substitution
WEAVER_LLM_KEY="${WEAVER_LLM_KEY:-$(python3 -c "import secrets; print(secrets.token_hex(24))")}"
CaddyHash=$(caddy hash-password --plaintext "${WEAVER_DASH_PASSWORD:-weaver-admin-change-me}" 2>/dev/null || echo "")

sudo mkdir -p /etc/caddy
sudo tee /etc/caddy/Caddyfile > /dev/null << CADDYEOF
# Weaver Azure Caddyfile
# Generated by setup_azure.sh

(weaver_security_headers) {
    header {
        -Server
        Strict-Transport-Security "max-age=31536000; includeSubDomains"
        X-Content-Type-Options "nosniff"
        X-Frame-Options "DENY"
        Referrer-Policy "no-referrer"
        Permissions-Policy "camera=(self), microphone=(self)"
        Content-Security-Policy "default-src 'self'; base-uri 'self'; object-src 'none'; frame-ancestors 'none'; form-action 'self'; script-src 'self'; style-src 'self'; img-src 'self' data: blob: https://weaverassets.blob.core.windows.net; media-src 'self' blob:; font-src 'self' data:; worker-src 'self' blob:; connect-src 'self' wss://${ORACLE_HOST} wss://${WEAVER_HEADLESS_HOST} https://weaverassets.blob.core.windows.net"
    }
}

${ORACLE_HOST} {
    encode zstd gzip
    import weaver_security_headers

    handle_path /brain/* {
        @bdenied {
            not {
                header X-Weaver-Key {$WEAVER_LLM_KEY}
            }
        }
        respond @bdenied 403
        header >Cache-Control "no-store"
        reverse_proxy 127.0.0.1:8093 {
            transport http {
                dial_timeout 3s
                response_header_timeout 130s
            }
        }
    }

    handle_path /tts/* {
        @tdenied {
            not {
                header X-Weaver-Key {$WEAVER_LLM_KEY}
            }
        }
        respond @tdenied 403
        header >Cache-Control "no-store"
        reverse_proxy 127.0.0.1:8092 {
            transport http {
                dial_timeout 3s
                response_header_timeout 240s
            }
        }
    }

    handle_path /codebase/* {
        @cdenied {
            not {
                header X-Weaver-Key {$WEAVER_LLM_KEY}
            }
        }
        respond @cdenied 403
        header >Cache-Control "no-store"
        reverse_proxy 127.0.0.1:8091 {
            transport http {
                dial_timeout 3s
                response_header_timeout 15s
            }
        }
    }

    handle {
        root * /var/www/weaver
        file_server
    }
}

${WEAVER_HEADLESS_HOST} {
    encode zstd gzip
    import weaver_security_headers

    handle_path /brain/* {
        @hbdenied {
            not {
                header X-Weaver-Key {$WEAVER_LLM_KEY}
            }
        }
        respond @hbdenied 403
        header >Cache-Control "no-store"
        reverse_proxy 127.0.0.1:8093
    }

    handle_path /tts/* {
        @htdenied {
            not {
                header X-Weaver-Key {$WEAVER_LLM_KEY}
            }
        }
        respond @htdenied 403
        header >Cache-Control "no-store"
        reverse_proxy 127.0.0.1:8092
    }

    handle {
        root * /var/www/weaver-headless
        file_server
    }
}

${WEAVER_DASH_HOST} {
    encode zstd gzip
    import weaver_security_headers
    header >Cache-Control "no-store"
    basic_auth {
        ydn ${CaddyHash}
    }
    reverse_proxy 127.0.0.1:9990
}

${WEAVER_STATUS_HOST} {
    encode zstd gzip
    import weaver_security_headers
    header >Cache-Control "no-store"
    basic_auth {
        ydn ${CaddyHash}
    }
    reverse_proxy 127.0.0.1:9996
}
CADDYEOF

# ── Step 9: Create /etc/default/caddy with env vars ─────────────────────────────
echo "--- Creating Caddy env file ---"
sudo tee /etc/default/caddy > /dev/null << DEFAULTEOF
WEAVER_LLM_KEY=${WEAVER_LLM_KEY}
WEAVER_DASH_HASH=${CaddyHash}
ORACLE_HOST=${ORACLE_HOST}
WEAVER_HEADLESS_HOST=${WEAVER_HEADLESS_HOST}
WEAVER_DASH_HOST=${WEAVER_DASH_HOST}
WEAVER_STATUS_HOST=${WEAVER_STATUS_HOST}
DEFAULTEOF

sudo systemctl enable caddy

# ── Step 10: Start services ─────────────────────────────────────────────────────
echo "--- Starting services ---"
sudo systemctl start weaver-llm.service
echo "Waiting for LLM to be ready..."
for i in $(seq 1 30); do
    if curl -sf http://127.0.0.1:8090/v1/models > /dev/null 2>&1; then
        echo "  LLM ready"
        break
    fi
    sleep 3
done

sudo systemctl start weaver-tts.service
sudo systemctl start weaver-brain.service
sudo systemctl start weaver.service
sudo systemctl start n8n.service
sudo systemctl start caddy

# ── Step 11: Verify ─────────────────────────────────────────────────────────────
echo ""
echo "=== Verification ==="
echo "LLM:       $(curl -sf http://127.0.0.1:8090/v1/models 2>/dev/null | head -c 120 || echo 'pending')"
echo "TTS:       $(curl -sf http://127.0.0.1:8092/health 2>/dev/null | head -c 80 || echo 'pending')"
echo "Brain:     $(curl -sf http://127.0.0.1:8093/health 2>/dev/null | head -c 80 || echo 'pending')"
echo "Caddy:     $(curl -sfI https://${ORACLE_HOST}/ 2>/dev/null | head -1 || echo 'pending')"
echo ""
echo "=== Setup Complete ==="
echo "Set DNS A records pointing to:"
echo "  $(curl -s ifconfig.me 2>/dev/null || echo '<get this VMs public IP>')"
echo ""
echo "All Weaver services are running. Check status with:"
echo "  sudo journalctl -u weaver-llm -u weaver -u weaver-brain -u weaver-tts -u caddy -u n8n -f"
echo ""
echo "Save WEAVER_LLM_KEY for browser configuration:"
echo "  $WEAVER_LLM_KEY"
